// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/qhai-dev/galio/library/galio"
	"github.com/qhai-dev/galio/rpc/account/server"
	"github.com/qhai-dev/galio/rpc/account/server/handler"
)

// Injectors from wire.go:

func initializer(application *galio.Application) error {
	accountService := handler.NewAccountService(application)
	error2 := server.NewRPCServer(accountService)
	return error2
}
